### ISSUE TITLE
Can't select Color Palette / Light Style Texture manually

### ISSUE THREAD

**Issue by DSVDiniz** [Error-mdl/Quake1BSPToUnity#1]
First of all, the tool is working great, I just had to do some minor fixes to get it working.
Maybe because I placed the project inside "/Assets/Plugins/" I had this issue:
I couldn't choose manually the Color Palette or Light Style Texture manually in the Q1 BSP Import window, I had to edit the script here to fix it:
![Screenshot_2021-09-08_11-48-31](https://user-images.githubusercontent.com/16140520/132532214-0a784514-aab6-4814-a016-0dfb451acadb.png)

**Comment by Error-mdl** [comment]
I forgot to actually set the values for the shader, palette, and lightstyle parameters with the values input from the editor window, so it would only show the parameter's current value and not actually let you change them. It should be fixed now.
